version: '3'
services:
  app:
    image: kaggle/python:latest
    container_name: Stable-Baselines3
    volumes:
      - ../src:/project/src
      - ../data:/project/data
      - ../model:/project/model
    working_dir: /project
    ports:
      - 8888:8888
    #command: apt-get install python-opengl ffmpeg freeglut3-dev xvfb
    #command: jupyter notebook --ip=0.0.0.0 --allow-root --no-browser